model:
  _target_: timm.create_model
  model_name: "convnextv2_base.fcmae_ft_in22k_in1k_384"
  num_classes: 17
  pretrained: true
  arcFace: false
  is_binary: false
  mid_freeze_epochs: 20
  all_freeze_epochs: 25